/**
 * Mappings of country names to country codes
 * @generated GPT-3.5
 * @author Filip Brebera w21020340
 */

export const countryMappings = {
  Australia: "AU",
  Austria: "AT",
  Bangladesh: "BD",
  Belgium: "BE",
  Brazil: "BR",
  Canada: "CA",
  China: "CN",
  Colombia: "CO",
  "Czech Republic": "CZ",
  Denmark: "DK",
  Ecuador: "EC",
  Egypt: "EG",
  Ethiopia: "ET",
  Finland: "FI",
  France: "FR",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  "Hong Kong": "HK",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Japan: "JP",
  Kazakhstan: "KZ",
  Kenya: "KE",
  "Korea, Republic of": "KR",
  Kuwait: "KW",
  Luxembourg: "LU",
  "Macedonia, The Former Yugoslav Republic of": "MK",
  Malaysia: "MY",
  Mexico: "MX",
  Mongolia: "MN",
  Namibia: "NA",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Norway: "NO",
  Pakistan: "PK",
  Paraguay: "PY",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  "Saudi Arabia": "SA",
  Singapore: "SG",
  Slovenia: "SI",
  "South Africa": "ZA",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Taiwan: "TW",
  "Tanzania, United Republic of": "TZ",
  Thailand: "TH",
  Turkey: "TR",
  Uganda: "UG",
  Ukraine: "UA",
  "United Kingdom": "GB",
  "United States": "US",
  "Viet Nam": "VN",
};
