<?php

/**
 * This is the main class of the application
 * It is responsible for autoloading all the files in the pkg directory
 * It is also responsible for handling the requests by calling the endpoint handler
 * @author Filip Brebera w21020340
 */

namespace Assessment;

class App
{
    private $autoloadedFiles = [];
    private $endpointHandler;

    public function __construct($endpointHandler)
    {
        $this->endpointHandler = $endpointHandler;
    }

    public function initRouter()
    {
        $this->endpointHandler->handle();
    }

    /**
     * This function is used for autoloading all the files in the pkg directory
     * @generated - This function is generated by the GPT-3.5 model
     */
    public function autoLoadFiles()
    {
        $this->autoloadedFiles = [];
        spl_autoload_register(function ($className) {
            $namespace = 'Assessment';

            foreach (AUTOLOAD_DIRECTORIES as $subNamespace => $directory) {
                $prefix = $namespace . '\\' . $subNamespace;

                if (strpos($className, $prefix) === 0) {
                    $relativeClass = substr($className, strlen($prefix));

                    $filename = str_replace('\\', '/', $relativeClass) . '.php';
                    $classFile = __DIR__ . '/pkg/' . $directory . $filename;

                    if (file_exists($classFile)) {
                        require_once($classFile);

                        $this->autoloadedFiles[$className] = $classFile;
                        return;
                    }
                }
            }
        });
    }
}
